kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: rabbit
nodes:
  - role: control-plane
  - role: worker
    labels:
      tier: rabbit-node
    extraPortMappings:
      - containerPort: 31672
        hostPort: 15672
      - containerPort: 30672
        hostPort: 5672
  - role: worker
    labels:
      tier: rabbit-node
  - role: worker
    labels:
      tier: rabbit-node
