apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app: rabbitmq
resources:
  - rabbitmq-namespace.yaml
  - rabbitmq-config.yaml
  - rabbitmq-erlang.yaml
  - rabbitmq-rbac.yaml
  - rabbitmq-service.yaml
  - rabbitmq-stateful-set.yaml
namespace: rabbits
