apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  enabled_plugins: |
    [rabbitmq_federation,rabbitmq_management,rabbitmq_management_agent,rabbitmq_peer_discovery_common,rabbitmq_web_dispatch,rabbitmq_peer_discovery_k8s,rabbitmq_shovel,rabbitmq_shovel_management].
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_formation.node_cleanup.interval = 15
    cluster_partition_handling = autoheal
    log.console = true
    log.console.level = info
    log.file.level = info
    queue_master_locator = min-masters
    vm_memory_high_watermark.relative = 0.800
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    disk_free_limit.relative = 2.0
    deprecated_features.permit.management_metrics_collection = true
    loopback_users.guest = false
