apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 31672
      name: http
    - port: 4369
      targetPort: 4369
      name: discovery
    - port: 5672
      targetPort: 5672
      name: amqp
      nodePort: 30672
  selector:
    app: rabbitmq
